# Summary of Analysis and Cleaning strategy 
- Review all Columns and null values 
- Change column names or lower case 
- Change column names from having '.' to '_' for easier read 
-

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

# Reading in coffee datasets

In [2]:
# Read the Arabica csv into a Pandas DataFrame
arabica_coffee_df = pd.read_csv('../Resources/arabica_data_cleaned.csv')
arabica_coffee_df.head()

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,2,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,3,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,4,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,5,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0

In [3]:
# Read the Robusta csv into a Pandas DataFrame
robusta_coffee_df = pd.read_csv('../Resources/robusta_data_cleaned.csv')
robusta_coffee_df.head()

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Robusta,ankole coffee producers coop,Uganda,kyangundu cooperative society,NaN,ankole coffee producers,0,ankole coffee producers coop,1488,...,Green,2,"June 26th, 2015",Uganda Coffee Development Authority,e36d0270932c3b657e96b7b0278dfd85dc0fe743,03077a1c6bac60e6f514691634a7f6eb5c85aae8,m,1488.0,1488.0,1488.0
1,2,Robusta,nishant gurjer,India,sethuraman estate kaapi royale,25,sethuraman estate,14/1148/2017/21,kaapi royale,3170,...,NaN,2,"October 31st, 2018",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,3170.0,3170.0,3170.0
2,3,Robusta,andrew hetzel,India,sethuraman estate,NaN,NaN,0000,sethuraman estate,1000m,...,Green,0,"April 29th, 2016",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,1000.0,1000.0,1000.0
3,4,Robusta,ugacof,Uganda,ugacof project area,NaN,ugacof,0,ugacof ltd,1212,...,Green,7,"July 14th, 2015",Uganda Coffee Development Authority,e36d0270932c3b657e96b7b0278dfd85dc0fe743,03077a1c6bac60e6f514691634a7f6eb5c85aae8,m,1212.0,1212.0,1212.0
4,5,Robusta,katuka development trust ltd,Uganda,katikamu capca farmers association,NaN,katuka development trust,0,katuka development trust ltd,1200-1300,...,Green,3,"June 26th, 2015",Uganda Coffee Development Authority,e36d0270932c3b657e96b7b0278dfd85dc0fe743,03077a1c6bac60e6f514691634a7f6eb5c85aae8,m,1200.0,1300.0,1250.0

# Comparing the arabica and robusta coffee dataframes

In [4]:
# Get a brief summary of Arabica dataFrame
arabica_coffee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1311 entries, 0 to 1310
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             1311 non-null   int64
 1   Species                1311 non-null   object
 2   Owner                  1304 non-null   object
 3   Country.of.Origin      1310 non-null   object
 4   Farm.Name              955 non-null    object
 5   Lot.Number             270 non-null    object
 6   Mill                   1001 non-null   object
 7   ICO.Number             1165 non-null   object
 8   Company                1102 non-null   object
 9   Altitude               1088 non-null   object
 10  Region                 1254 non-null   object
 11  Producer               1081 non-null   object
 12  Number.of.Bags         1311 non-null   int64
 13  Bag.Weight             1311 non-null   object
 14  In.Country.Partner     1311 non-null   object
 15  Harvest.Year           1264 non-null   object
 16  Grading.Date           1311 non-null   object
 17  Owner.1                1304 non-null   object
 18  Variety                1110 non-null   object
 19  Processing.Method      1159 non-null   object
 20  Aroma                  1311 non-null   float64
 21  Flavor                 1311 non-null   float64
 22  Aftertaste             1311 non-null   float64
 23  Acidity                1311 non-null   float64
 24  Body                   1311 non-null   float64
 25  Balance                1311 non-null   float64
 26  Uniformity             1311 non-null   float64
 27  Clean.Cup              1311 non-null   float64
 28  Sweetness              1311 non-null   float64
 29  Cupper.Points          1311 non-null   float64
 30  Total.Cup.Points       1311 non-null   float64
 31  Moisture               1311 non-null   float64
 32  Category.One.Defects   1311 non-null   int64
 33  Quakers                1310 non-null   float64
 34  Color                  1095 non-null   object
 35  Category.Two.Defects   1311 non-null   int64
 36  Expiration             1311 non-null   object
 37  Certification.Body     1311 non-null   object
 38  Certification.Address  1311 non-null   object
 39  Certification.Contact  1311 non-null   object
 40  unit_of_measurement    1311 non-null   object
 41  altitude_low_meters    1084 non-null   float64
 42  altitude_high_meters   1084 non-null   float64
 43  altitude_mean_meters   1084 non-null   float64
dtypes: float64(16), int64(4), object(24)
memory usage: 450.8+ KB

In [5]:
# Get a brief summary of Robusta dataFrame

robusta_coffee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             28 non-null     int64
 1   Species                28 non-null     object
 2   Owner                  28 non-null     object
 3   Country.of.Origin      28 non-null     object
 4   Farm.Name              25 non-null     object
 5   Lot.Number             6 non-null      object
 6   Mill                   20 non-null     object
 7   ICO.Number             17 non-null     object
 8   Company                28 non-null     object
 9   Altitude               25 non-null     object
 10  Region                 26 non-null     object
 11  Producer               26 non-null     object
 12  Number.of.Bags         28 non-null     int64
 13  Bag.Weight             28 non-null     object
 14  In.Country.Partner     28 non-null     object
 15  Harvest.Year           28 non-null     int64
 16  Grading.Date           28 non-null     object
 17  Owner.1                28 non-null     object
 18  Variety                3 non-null      object
 19  Processing.Method      10 non-null     object
 20  Fragrance...Aroma      28 non-null     float64
 21  Flavor                 28 non-null     float64
 22  Aftertaste             28 non-null     float64
 23  Salt...Acid            28 non-null     float64
 24  Bitter...Sweet         28 non-null     float64
 25  Mouthfeel              28 non-null     float64
 26  Uniform.Cup            28 non-null     float64
 27  Clean.Cup              28 non-null     float64
 28  Balance                28 non-null     float64
 29  Cupper.Points          28 non-null     float64
 30  Total.Cup.Points       28 non-null     float64
 31  Moisture               28 non-null     float64
 32  Category.One.Defects   28 non-null     int64
 33  Quakers                28 non-null     int64
 34  Color                  26 non-null     object
 35  Category.Two.Defects   28 non-null     int64
 36  Expiration             28 non-null     object
 37  Certification.Body     28 non-null     object
 38  Certification.Address  28 non-null     object
 39  Certification.Contact  28 non-null     object
 40  unit_of_measurement    28 non-null     object
 41  altitude_low_meters    25 non-null     float64
 42  altitude_high_meters   25 non-null     float64
 43  altitude_mean_meters   25 non-null     float64
dtypes: float64(15), int64(6), object(23)
memory usage: 9.8+ KB

In [6]:
# Compare column names to identify differences between datasets
# ------------------------------------------------

# Get column names of each DataFrame
columns_dfa = set(arabica_coffee_df.columns)
columns_dfr = set(robusta_coffee_df.columns)

# Compare column names
common_columns = columns_dfa.intersection(columns_dfr)
unique_columns_dfa = columns_dfa - columns_dfr
unique_columns_dfr = columns_dfr - columns_dfa

# Print the results
print("Common columns:", common_columns)
print("Columns unique to dfa:", unique_columns_dfa)
print("Columns unique to dfr:", unique_columns_dfr)

Common columns: {'Expiration', 'Grading.Date', 'Category.Two.Defects', 'Altitude', 'Total.Cup.Points', 'Owner.1', 'In.Country.Partner', 'Mill', 'altitude_low_meters', 'unit_of_measurement', 'Certification.Contact', 'Unnamed: 0', 'altitude_mean_meters', 'Flavor', 'Company', 'Harvest.Year', 'Region', 'Producer', 'Balance', 'ICO.Number', 'Owner', 'Number.of.Bags', 'altitude_high_meters', 'Processing.Method', 'Country.of.Origin', 'Moisture', 'Certification.Address', 'Bag.Weight', 'Lot.Number', 'Farm.Name', 'Quakers', 'Species', 'Aftertaste', 'Category.One.Defects', 'Variety', 'Color', 'Clean.Cup', 'Cupper.Points', 'Certification.Body'}
Columns unique to dfa: {'Sweetness', 'Body', 'Uniformity', 'Aroma', 'Acidity'}
Columns unique to dfr: {'Bitter...Sweet', 'Uniform.Cup', 'Salt...Acid', 'Fragrance...Aroma', 'Mouthfeel'}

In [7]:
# Change the names of columns in Robusta dataframe to match relevent columns in Arabica dataframe
# ------------------------------------------------

# Change names
robusta_coffee_df = robusta_coffee_df.rename(columns={'Fragrance...Aroma': 'Aroma',
                                                      'Salt...Acid':'Acidity',
                                                      'Uniform.Cup':'Uniformity',
                                                      'Mouthfeel':'Body',
                                                     'Bitter...Sweet':'Sweetness'})

# Check dataframe
robusta_coffee_df.head()

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,1,Robusta,ankole coffee producers coop,Uganda,kyangundu cooperative society,NaN,ankole coffee producers,0,ankole coffee producers coop,1488,...,Green,2,"June 26th, 2015",Uganda Coffee Development Authority,e36d0270932c3b657e96b7b0278dfd85dc0fe743,03077a1c6bac60e6f514691634a7f6eb5c85aae8,m,1488.0,1488.0,1488.0
1,2,Robusta,nishant gurjer,India,sethuraman estate kaapi royale,25,sethuraman estate,14/1148/2017/21,kaapi royale,3170,...,NaN,2,"October 31st, 2018",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,3170.0,3170.0,3170.0
2,3,Robusta,andrew hetzel,India,sethuraman estate,NaN,NaN,0000,sethuraman estate,1000m,...,Green,0,"April 29th, 2016",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,1000.0,1000.0,1000.0
3,4,Robusta,ugacof,Uganda,ugacof project area,NaN,ugacof,0,ugacof ltd,1212,...,Green,7,"July 14th, 2015",Uganda Coffee Development Authority,e36d0270932c3b657e96b7b0278dfd85dc0fe743,03077a1c6bac60e6f514691634a7f6eb5c85aae8,m,1212.0,1212.0,1212.0
4,5,Robusta,katuka development trust ltd,Uganda,katikamu capca farmers association,NaN,katuka development trust,0,katuka development trust ltd,1200-1300,...,Green,3,"June 26th, 2015",Uganda Coffee Development Authority,e36d0270932c3b657e96b7b0278dfd85dc0fe743,03077a1c6bac60e6f514691634a7f6eb5c85aae8,m,1200.0,1300.0,1250.0

In [8]:
# Check differences once more
# ------------------------------------------------

# Get column names of each DataFrame
columns_dfa = set(arabica_coffee_df.columns)
columns_dfr = set(robusta_coffee_df.columns)

# Compare column names
common_columns = columns_dfa.intersection(columns_dfr)
unique_columns_dfa = columns_dfa - columns_dfr
unique_columns_dfr = columns_dfr - columns_dfa

# Print the results
print("Common columns:", common_columns)
print("Columns unique to dfa:", unique_columns_dfa)
print("Columns unique to dfr:", unique_columns_dfr)

Common columns: {'Expiration', 'Grading.Date', 'Category.Two.Defects', 'Altitude', 'Total.Cup.Points', 'Owner.1', 'In.Country.Partner', 'Mill', 'altitude_low_meters', 'Aroma', 'unit_of_measurement', 'Certification.Contact', 'Acidity', 'Unnamed: 0', 'altitude_mean_meters', 'Flavor', 'Body', 'Company', 'Harvest.Year', 'Region', 'Producer', 'Balance', 'ICO.Number', 'Owner', 'Number.of.Bags', 'Sweetness', 'altitude_high_meters', 'Processing.Method', 'Country.of.Origin', 'Moisture', 'Certification.Address', 'Bag.Weight', 'Lot.Number', 'Farm.Name', 'Uniformity', 'Quakers', 'Species', 'Aftertaste', 'Category.One.Defects', 'Variety', 'Color', 'Clean.Cup', 'Cupper.Points', 'Certification.Body'}
Columns unique to dfa: set()
Columns unique to dfr: set()

In [9]:
# Append both dataframes to each other

coffee_df = pd.concat([arabica_coffee_df, robusta_coffee_df], ignore_index=True)

coffee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             1339 non-null   int64
 1   Species                1339 non-null   object
 2   Owner                  1332 non-null   object
 3   Country.of.Origin      1338 non-null   object
 4   Farm.Name              980 non-null    object
 5   Lot.Number             276 non-null    object
 6   Mill                   1021 non-null   object
 7   ICO.Number             1182 non-null   object
 8   Company                1130 non-null   object
 9   Altitude               1113 non-null   object
 10  Region                 1280 non-null   object
 11  Producer               1107 non-null   object
 12  Number.of.Bags         1339 non-null   int64
 13  Bag.Weight             1339 non-null   object
 14  In.Country.Partner     1339 non-null   object
 15  Harvest.Year           1292 non-null   object
 16  Grading.Date           1339 non-null   object
 17  Owner.1                1332 non-null   object
 18  Variety                1113 non-null   object
 19  Processing.Method      1169 non-null   object
 20  Aroma                  1339 non-null   float64
 21  Flavor                 1339 non-null   float64
 22  Aftertaste             1339 non-null   float64
 23  Acidity                1339 non-null   float64
 24  Body                   1339 non-null   float64
 25  Balance                1339 non-null   float64
 26  Uniformity             1339 non-null   float64
 27  Clean.Cup              1339 non-null   float64
 28  Sweetness              1339 non-null   float64
 29  Cupper.Points          1339 non-null   float64
 30  Total.Cup.Points       1339 non-null   float64
 31  Moisture               1339 non-null   float64
 32  Category.One.Defects   1339 non-null   int64
 33  Quakers                1338 non-null   float64
 34  Color                  1121 non-null   object
 35  Category.Two.Defects   1339 non-null   int64
 36  Expiration             1339 non-null   object
 37  Certification.Body     1339 non-null   object
 38  Certification.Address  1339 non-null   object
 39  Certification.Contact  1339 non-null   object
 40  unit_of_measurement    1339 non-null   object
 41  altitude_low_meters    1109 non-null   float64
 42  altitude_high_meters   1109 non-null   float64
 43  altitude_mean_meters   1109 non-null   float64
dtypes: float64(16), int64(4), object(24)
memory usage: 460.4+ KB

# Refining column names 
- changing all column names to lower case 
- changing all '.' to '_' for easier read

In [10]:
# lower case all column names for ease of access 
coffee_df.columns = coffee_df.columns.str.lower()

# Replace all '.' to '_' for easier read 
coffee_df.columns = coffee_df.columns.str.replace('.','_')

# confirm all columns renamed
coffee_df.columns

C:\Users\admin\AppData\Local\Temp\ipykernel_18108\742622886.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  coffee_df.columns = coffee_df.columns.str.replace('.','_')

Index(['unnamed: 0', 'species', 'owner', 'country_of_origin', 'farm_name',
       'lot_number', 'mill', 'ico_number', 'company', 'altitude', 'region',
       'producer', 'number_of_bags', 'bag_weight', 'in_country_partner',
       'harvest_year', 'grading_date', 'owner_1', 'variety',
       'processing_method', 'aroma', 'flavor', 'aftertaste', 'acidity', 'body',
       'balance', 'uniformity', 'clean_cup', 'sweetness', 'cupper_points',
       'total_cup_points', 'moisture', 'category_one_defects', 'quakers',
       'color', 'category_two_defects', 'expiration', 'certification_body',
       'certification_address', 'certification_contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [11]:
# drop unnecessary columns 
coffee_df = coffee_df.drop(columns=['unnamed: 0', 'owner', 'lot_number', 'mill', 'uniformity', 'farm_name', 'producer', 'total_cup_points',  'cupper_points', 'ico_number', 'cupper_points', 'company', 'altitude', 'number_of_bags', 'bag_weight', 'in_country_partner', 'harvest_year', 'grading_date', 'owner_1', 'moisture', 'category_one_defects', 'quakers', 'color', 'category_two_defects', 'expiration', 'certification_body', 'certification_address', 'certification_contact', 'unit_of_measurement', 'altitude_mean_meters'])

In [12]:
# check columns
coffee_df.columns

Index(['species', 'country_of_origin', 'region', 'variety',
       'processing_method', 'aroma', 'flavor', 'aftertaste', 'acidity', 'body',
       'balance', 'clean_cup', 'sweetness', 'altitude_low_meters',
       'altitude_high_meters'],
      dtype='object')

In [13]:
# Change 'null values' from 'variety' column to 'unknown'
coffee_df['variety'] = coffee_df['variety'].fillna('Unknown')

In [14]:
# Delete null-values from appended dataframe
coffee_df = coffee_df.dropna()

# Data Cleaning

In [15]:
# remove text after / in 'processing_method' column
coffee_df['processing_method'] = coffee_df['processing_method'].str.split('/').str[0]

In [16]:
# change altitude_low_meters to int datatype
coffee_df['altitude_low_meters'] = coffee_df['altitude_low_meters'].astype(int)

In [17]:
# change altitude_high_meters to int datatype
coffee_df['altitude_high_meters'] = coffee_df['altitude_high_meters'].astype(int)

In [18]:
# Identify unique values
# ------------------------------------------------

# Create an empty dictionary to store unique values for each column
unique_values = {}

# Loop through the columns and find unique values
for column in coffee_df.columns:
    unique_values[column] = coffee_df[column].unique()

# Display unique values for each column
for column, values in unique_values.items():
    print(f'Column: {column}')
    print(values)
    print('\n')

Column: species
['Arabica' 'Robusta']


Column: country_of_origin
['Ethiopia' 'United States' 'China' 'Costa Rica' 'Mexico' 'Brazil'
 'Uganda' 'Taiwan' 'Kenya' 'Thailand' 'Colombia' 'Panama' 'Guatemala'
 'Papua New Guinea' 'El Salvador' 'Indonesia'
 'Tanzania, United Republic Of' 'Honduras' 'Japan' 'Nicaragua' 'Ecuador'
 'United States (Puerto Rico)' 'Haiti' 'Burundi' 'Vietnam' 'Philippines'
 'Rwanda' 'Malawi' 'Laos' 'Zambia' 'Myanmar' 'Cote d?Ivoire' 'Peru'
 'India']


Column: region
['guji-hambela' 'oromia' 'snnp/kaffa zone,gimbowereda' 'antioquia'
 'yunnan' 'gedio' 'san ramon' 'xalapa' 'south of minas'
 'kapchorwa eastern' 'leye, alishan township, chiayi county'
 'vale da grama' 'west and central valley' 'muranga' 'chiang rai'
 'natou county' 'nyeri' 'tolima' 'kiambu' 'sipi, mt elgon' 'eastern'
 'huila' 'boquete' 'acatenango' 'nuevo oriente'
 'eastern highlands province' 'apaneca'
 'ataco, apaneca - ilamatepec mountain range' 'kirinyaga'
 'bulambuli eastern region' 'huehuetenango' 'kapchorwa' 'west valley'
 'central kenya' 'santander' 'lintong' 'pasto' 'aricha' 'cundinamarca'
 'eastern uganda' 'tarrazu' 'veracruz' 'grama valley' 'mbeya' 'coatepec'
 'dongshan dist., tainan city 臺南市東山區' 'marcala' 'temanggung, indonesia'
 'ada okinawa japan' 'yirgacheffe' 'costa rica' 'taichung xinshe 台中市新社區'
 'oriente' 'el remudadero' 'mbale' 'jalapa' 'tres rios'
 'mountains of minas gerais' 'valle central' 'cauca' 'hustusco'
 'jaltenango' 'sumatra brastagi' 'mountain ali, taiwan' 'tapachula'
 'central region' 'tuxtla gutierrez' '國姓鄉 guoshing township'
 'chiang rai thailand' 'nariño' 'antigua' 'shizingo village'
 'san pedro cotzilnam' 'la concordia, chiapas' 'kasese' 'san marcos'
 'solola' 'norte' 'jinotega' 'cerrado'
 'snnprg; kafa; telo woreda; shada kebele' 'arusha' 'kenya'
 'minas gerais, br' 'mt. rwenzori' 'nanxi dist., tainan city 臺南市楠西區'
 'aldea xeucalvitz, ixil region, quiche department'
 'santo domingo cacalotepec' 'ethiopia, sidamo' 'sidamo' 'comayagua'
 'blend' 'chiangrai' 'leye, alishan township, chiayi county 嘉義阿里山樂野村'
 '台中和平區' 'xicotepec de juarez' 'la concordia' 'la yerbabuena'
 'central valley' 'province of manabi, ecuador' 'petatlan'
 'carmo de minas' '台南市東山區 (dongshan dist., tainan city)' 'west nile'
 'yauco region' 'huazalingo, hidalgo' 'quetzaltenango' 'meru county'
 'thailand' 'huila supremo' 'east java' 'sacatepequez, guatemala'
 'chiapas, jaltenango' 'pitalito' 'nkure- meru' 'bener meriah' 'atitlan'
 'chilón' 'totutla' 'karatu northern' 'chiapas' 'thiotte, haiti' 'kayanza'
 'sierra madre occidental' 'cuarenteño' '南投國姓' 'eje cafetero'
 'fortín de las flores' 'la plata' 'moshi' 'dala' 'dehong prefecture'
 'mbinga' 'kilimanjaro' 'tlanchinol, hidalgo' 'san bartolo tutotepec'
 'san isidro' 'mogiana' 'chiayi alishan 嘉義縣阿里山鄉' 'santa catarina juquila'
 'kasese, mt. rwenzori' 'vietnam cau dat' 'el tumbador, san marcos'
 'high mogiana' '嘉義阿里山' 'sul de minas' 'atoyac de alvarez'
 'la reforma, san marcos' 'guayata' 'blida,kercha,guji,oromia' '台東太麻里'
 'bukidnon, mindanao, philppines' 'asia pacific' 'don duong' 'la cumbre'
 'el balsamo, quezaltepec' 'gicumbi' 'vietnam tutra' 'berastagi'
 'santa rosa' 'sapan toraja' 'el progreso'
 '台南市東山區( dongshan dist., tainan city)' 'cacahuatique' 'menglian' 'mzuzu'
 'south huila' 'paksong,laos' 'karatu arusha' 'la yerba' 'mt elgon'
 'phahi' 'mahuixtlan' 'aceh' 'ikand village' 'oaxaca' 'colima' 'bali'
 'zapotitlan de mendez' 'comayagua, honduras' 'arusha meru'
 'zihuatanejo de azueta' 'progreso santa rosa teocelo' 'fln mirador'
 'xishuangbanna prefecture' 'changhua baguashan 彰化市八卦山'
 'jaltocan, hidalgo' 'brazil matas de minas' 'nantou' 'calnali, hidalgo'
 'juquila' 'canoas' 'ruvuma' 'northern' 'ilomba vilage, mbozi'
 'yunlin 雲林縣石壁' 'altotonga' 'aceh gayo' 'ngorogoro' 'turrialba'
 'el paraíso' 'guinope el paraíso' 'lao p.d.r.' 'meru' 'occidental'
 'coscomatepec' 'monte carmelo' 'mubuyu estate' 'chapulhuacan, hidalgo'
 'ywar ngan' 'lington nihuta' 'kakoma'
 'siltepec el triunfo, chiapas, mexico' 'vietnam'
 'tenango de doria, hidalgo' 'tepictla' 'yajalon'
 'sacún palma, municipio de chilón, chiapas' 'western region'
 'oldeani , mongola' '古坑鄉荷包村尖山坑60號' 'ywar ngan township' 'dondon, haiti'
 'amatenango de la frontera' 'temaxcalapa' 'manzanillo' 'ijen' '苗栗三灣'
 'san lucas toliman, solola' 'siltepec el triunfo' 'coatepec, coatepec'
 'mantiqueira de minas' 'davao city, region 11' 'matas de minas        '
 'dongshan dist., tainan city 台南市東山區' 'karatu ngorogoro' 'motozintla'
 'dipilto, nueva segovia' 'ruvuma, mbinga' 'corillera administrative'
 'southern- zomba' 'alta paulista (sao paulo)' 'central america'
 'iwala village, mbeya rural' 'naranjo' 'san fernando'
 'santo reyes nopala' 'santa maria sitepec' 'talpa de allende'
 'motozintla, chiapas' 'adolfo lopez mateos' 'taiwan' 'pyinoolwin'
 'manyara, karatu' '台中新社' 'matagalpa' 'taichung taiping 台中市太平區'
 'new taipei zhonghe 新北市中和區' 'ixhuatlan del cafe' 'orient'
 'siguatepeque, comayagua' 'haiti'
 'el desmoronado, talpan de allende jalisco' 'ocotepeque' 'pyin oo lwin'
 'zaragoza itundujia'
 'department of ahuachapan, municipality of apanecallamatepec mountain'
 'pochutla' 'mkuu rombo' 'cerrado - monte carmelo - minas gerais'
 'yauk sauk, shan state' 'chiayi fanlu嘉義縣番路鄉' '苗栗泰安'
 'yunlin gukeng he bao 雲林縣古坑鄉荷苞村' 'escuitla' 'doe kwin, pyin oo lwin'
 'sierra fraylesca, chiapas' 'san miguel del puerto'
 'taiwu township , pingtung county 屏東縣泰武鄉'
 'baihe dist., tainan city 臺南市白河區' 'brunca' 'tepetzingo'
 'cnra station of divo' 'pereira' 'zentla' 'occidente' 'tlacuilotepec'
 'intibuca' 'san ignacio' 'iliatenco, guerrero' 'ohuapan, tlaltetela'
 'yecuatla' 'cofradia de suchitlan' 'sierra, chiapas'
 'villa talea de castro' 'los angeles' 'xochitonalco, huautla        '
 'cordoba' 'indonesia' 'benguet, mountain province' 'ocosingo'
 'huautla de jimenez' 'chocaman, veracruz' 'sierra alta mixe y zapoteca'
 'tlatlauquitepec' 'sierra norte yajalon, chiapas' 'juchique de ferrer'
 "department d'artibonite , haiti" 'chikmagalur karnataka indua'
 'chikmagalur karnataka india' 'chikmagalur karnataka' 'chikmagalur'
 'kwanza norte province, angola']


Column: variety
['Unknown' 'Other' 'Catimor' 'Ethiopian Yirgacheffe' 'Caturra' 'Bourbon'
 'SL14' 'Sumatra' 'SL34' 'SL28' 'Gesha' 'Catuai' 'Pacamara'
 'Sumatra Lintong' 'Typica' 'Mundo Novo' 'Java' 'Peaberry' 'Pacas'
 'Mandheling' 'Yellow Bourbon' 'Ruiru 11' 'Ethiopian Heirlooms'
 'Moka Peaberry' 'Arusha' 'Sulawesi' 'Marigojipe' 'Blue Mountain'
 'Pache Comun']


Column: processing_method
['Washed ' 'Natural ' 'Pulped natural ' 'Semi-washed ' 'Other']


Column: aroma
[8.67 8.75 8.17 8.25 8.08 8.   8.42 8.5  7.67 7.83 8.33 7.75 7.92 7.58
 7.42 7.33 7.5  7.25 7.17 7.08 5.08 6.92 7.   6.83 6.75 6.5  6.33 6.67]


Column: flavor
[8.83 8.67 8.58 8.5  8.42 8.25 8.17 8.33 8.   7.83 8.08 7.92 7.75 7.58
 7.67 7.5  7.42 7.33 7.25 7.08 7.   7.17 6.92 6.67 6.83 6.75 6.5  6.58
 6.33 6.42 6.17]


Column: aftertaste
[8.67 8.5  8.42 8.25 8.17 8.33 8.58 8.08 8.   7.92 7.83 7.75 7.67 7.58
 7.42 7.5  7.33 7.25 7.17 7.08 7.   6.83 6.92 6.75 6.58 6.67 6.33 6.5
 6.17 6.42 6.25]


Column: acidity
[8.75 8.58 8.42 8.5  8.33 8.17 8.   8.25 7.75 8.08 7.92 7.83 7.67 7.58
 7.42 7.17 7.5  7.25 7.33 7.08 6.92 5.25 7.   6.83 6.75 6.08 6.67 6.5
 6.25]


Column: body
[8.5  8.42 7.67 7.75 8.08 8.   8.17 7.92 8.25 7.83 7.58 7.5  7.33 7.42
 7.25 7.17 7.   7.08 8.33 6.75 6.83 6.92 6.67 6.33 6.5  6.42]


Column: balance
[8.42 8.25 8.33 8.17 8.08 8.   7.92 7.83 7.75 8.58 8.5  7.67 7.58 7.5
 7.33 7.42 7.17 7.25 6.83 7.08 7.   6.92 6.58 6.75 6.33 6.67 6.5  6.17
 6.08]


Column: clean_cup
[10.    9.33  6.67  8.67  8.    5.33  7.33  6.    2.67  0.    1.33]


Column: sweetness
[10.    9.33  8.67  6.67  8.    6.    1.33  7.92  7.75  7.83  7.42  7.58]


Column: altitude_low_meters
[  1950   1800   1795   1855   1872   1943   2080   1450   1700   2019
   1300   1320   2112   1250   1200   1750   1941   1000   1754    900
   1520   1400   1600   1524   1417   1500   1680   1900   1706   1770
   1550   2560   2136   1580   1100    800   1620    350   1350    170
   1150   2000   1310   1219    442   1099   1170   1116   1565   3280
   1850   1545   1530      1    894    968   1480   1658   1260   1650
    890    934    950   2527    480   1218    750    853    700   1356
   1128   1799    940   1402    439   1330   1813   1227   1280   1880
   2100   1261   1483    175   1901    168   1653    532   1089   1380
    905    872   1473   1645   1371    775   1059  11000   1248   1040
    157    650   1442    165   1296   1240   1050   1317   1679   2285
   1560   1396    982   1268   1676    200    600    441   1180   1338
    533   1390   1144     13    944   2500   1020   1877    981    690
    973   4001   1556    774    150 190164    850    160   1599    400
    125    110   1422    763    680    100    990    695   1456   1642
    758   1525   1066    550    688    300   1186   1210   3825 110000
    185   1383     50   3800   1859    995    914   4287    808    250
   3845    500   1022    975   1264     12   3500   1140   3170   3140
   3000    795]


Column: altitude_high_meters
[  2200   1850   1955   1872   1943   2080   1450   2000   2019   1300
   1320   2112   1250   1950   1200   1800   1941   1000   1754   1500
   1900   1600   1524   1417   1700   1400   1680   1755   1770   1550
   2560   2136   1580   1100    800   1620    350   1350    170   1150
   1750   1310   1219    900    442   1099   1170   1116   1565   3280
   1668   1530    500   1183    968   1480   1260   1650    890    934
    950   2527      1    570   1703   1218    750    853    700   1356
   1128   1799    940   1402    439   1330   1813   1227   1280   1880
   2100   1261   1483    175   1901    168   1653    532   1089   1380
    905    894    872   1473   1645   1371    775   1059  11000   1248
   1040    157    650   1442    165   1296   1240   1050   1317   1679
   2285   1560   1396    982   1268   1676    200    600   1828    441
   1180   1338    533   1390   1144     13    944   2500   1020   1877
    981    690    973   4001   1556    774    150 190164    850   1599
    125    110   1422    763    680    695   1706   1456   1642    758
   1525   1066    550    688    300   1186   1210    100   3825 110000
    185   1383     50   3800   1859    995    914   4287    808   1275
    250   3845   1022    975   1264     12   3500   1140   3170   3140
   3000    795]

In [19]:
replacement_dict = {'Ethiopian Yirgacheffe': 'Yirgacheffe',
                    'Ethiopian Heirlooms': 'Heirloom',
                    'Sumatra Lintong': 'Lintong',
                    'ada okinawa japan': 'okinawa',
                    'lintong': 'sumatra',
                    'sumatra brastagi': 'sumatra',
                    'snnprg; kafa; telo woreda; shada kebele': 'kaffa zone'
                   }

# Iterate through the dictionary and replace values in the correct columns
for old_value, new_value in replacement_dict.items():
    coffee_df['region'] = coffee_df['region'].replace(old_value, new_value)
    coffee_df['variety'] = coffee_df['variety'].replace(old_value, new_value)

In [20]:
# Define regex patterns
patterns_for_column = {'region': [',.*', '([^,]*,[^,]*),.*']}

# Iterate through columns
for column in coffee_df.columns:
    if column in patterns_for_column:
        for pattern in patterns_for_column['region']:
            # Check if the current regex pattern is present in any cell of the column
            if coffee_df['region'].str.contains(pattern).any():
                # If found, update the values using the regex pattern
                coffee_df['region'] = coffee_df['region'].replace(pattern, '', regex=True)
                #break  # Stop checking with other patterns for this column

# Display the result DataFrame
coffee_df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_18108\2689032396.py:9: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  if coffee_df['region'].str.contains(pattern).any():

,species,country_of_origin,region,variety,processing_method,aroma,flavor,aftertaste,acidity,body,balance,clean_cup,sweetness,altitude_low_meters,altitude_high_meters
0,Arabica,Ethiopia,guji-hambela,Unknown,Washed,8.67,8.83,8.67,8.75,8.50,8.42,10.0,10.0,1950,2200
1,Arabica,Ethiopia,guji-hambela,Other,Washed,8.75,8.67,8.50,8.58,8.42,8.42,10.0,10.0,1950,2200
3,Arabica,Ethiopia,oromia,Unknown,Natural,8.17,8.58,8.42,8.42,8.50,8.25,10.0,10.0,1800,2200
4,Arabica,Ethiopia,guji-hambela,Other,Washed,8.25,8.50,8.25,8.50,8.42,8.33,10.0,10.0,1950,2200
9,Arabica,Ethiopia,snnp/kaffa zone,Other,Natural,8.08,8.58,8.50,8.50,7.67,8.42,10.0,10.0,1795,1850

In [21]:
# Convert all text to lowercase
coffee_df = coffee_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
coffee_df = coffee_df.applymap(lambda x: x.lower() if isinstance(x, str) else x)
coffee_df = coffee_df.applymap(lambda x: x.replace(' ', '_') if isinstance(x, str) else x)
coffee_df = coffee_df.applymap(lambda x: x.replace(';', '_') if isinstance(x, str) else x)
coffee_df = coffee_df.applymap(lambda x: x.replace('-', '_') if isinstance(x, str) else x)
coffee_df.head()

,species,country_of_origin,region,variety,processing_method,aroma,flavor,aftertaste,acidity,body,balance,clean_cup,sweetness,altitude_low_meters,altitude_high_meters
0,arabica,ethiopia,guji_hambela,unknown,washed,8.67,8.83,8.67,8.75,8.50,8.42,10.0,10.0,1950,2200
1,arabica,ethiopia,guji_hambela,other,washed,8.75,8.67,8.50,8.58,8.42,8.42,10.0,10.0,1950,2200
3,arabica,ethiopia,oromia,unknown,natural,8.17,8.58,8.42,8.42,8.50,8.25,10.0,10.0,1800,2200
4,arabica,ethiopia,guji_hambela,other,washed,8.25,8.50,8.25,8.50,8.42,8.33,10.0,10.0,1950,2200
9,arabica,ethiopia,snnp/kaffa_zone,other,natural,8.08,8.58,8.50,8.50,7.67,8.42,10.0,10.0,1795,1850

In [22]:
#coffee_df.to_csv('../Resources/coffee_final.csv', index=False)

In [23]:
from geopy.geocoders import Nominatim

def get_lat_lon_for_country(country_name):
    geolocator = Nominatim(user_agent="country_locator")
    location = geolocator.geocode(country_name)
    
    if location:
        return location.latitude, location.longitude
    else:
        return None

# Create new columns for latitude and longitude
coffee_df['latitude'] = None
coffee_df['longitude'] = None

# Iterate through rows and geocode each country
for index, row in coffee_df.iterrows():
    country_name = row['country_of_origin']  # Replace 'CountryColumnName' with the actual column name in your CSV
    lat_lon = get_lat_lon_for_country(country_name)
    
    if lat_lon:
        coffee_df.at[index, 'latitude'] = lat_lon[0]
        coffee_df.at[index, 'longitude'] = lat_lon[1]

coffee_df.head()

KeyboardInterrupt:

# Data Exploration

In [ ]:
coffee_df.info()

In [ ]:
coffee_df.describe().T

In [ ]:
coffee_df.isnull().sum()

In [ ]:
coffee_df.hist(bins=20, figsize=(10, 10))
plt.show()

In [ ]:
import seaborn as sb
plt.figure(figsize=(12, 12))
sb.heatmap(coffee_df.corr() > 0.7, annot=True, cbar=False)
plt.show()